# Generated by Django 5.2.1 on 2025-06-01 16:14

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='comment',
            field=tinymce.models.HTMLField(),
        ),
    ]
